/**
 * Order Repository
 * CRUD operations for orders with Supabase
 */

import { supabaseAdmin, isSupabaseConfigured, withErrorHandling } from '../db';
import { Order, OrderInsert, OrderUpdate, OrderStatus } from '../db-types';
import { generateOrderCode } from '../sepay-utils';

export interface CreateOrderData {
    fullName: string;
    email: string;
    phone: string;
    telegram: string;
    birthday?: string;
    gender?: string;
    address?: string;
    note?: string;
    program: string;
    programId?: number;
    price?: number;
    programData?: Record<string, any>;
    courseName?: string;
    couponCode?: string;
}

export interface OrderWithTransaction extends Order {
    transaction?: {
        id: number;
        status: string;
        gateway_transaction_id: string | null;
        qr_code_url: string | null;
    } | null;
}

export const OrderRepository = {
    /**
     * Create a new order
     */
    async create(data: CreateOrderData): Promise<Order> {
        if (!isSupabaseConfigured()) {
            throw new Error('Supabase is not configured');
        }

        // Generate order code for payment reference (stored in program_data, NOT in code field)
        // The 'code' column is UUID and auto-generated by database
        const orderCode = generateOrderCode();

        const insertData: OrderInsert = {
            // Note: 'code' field is UUID and auto-generated, don't set it
            full_name: data.fullName,
            email: data.email,
            phone: data.phone,
            telegram: data.telegram,
            birthday: data.birthday,
            gender: data.gender,
            address: data.address,
            note: data.note,
            program: data.program,
            program_id: data.programId,
            price: data.price,
            program_data: { ...data.programData, orderCode }, // Store orderCode here
            status: OrderStatus.PENDING,
            course_name: data.courseName,
            coupon_code: data.couponCode,
        };

        const { data: order, error } = await supabaseAdmin
            .from('order')
            .insert(insertData)
            .select()
            .single();

        if (error) {
            console.error('Error creating order:', error);
            throw new Error(`Failed to create order: ${error.message}`);
        }

        return order;
    },

    /**
     * Get order by ID
     */
    async getById(id: number): Promise<Order | null> {
        if (!isSupabaseConfigured()) {
            throw new Error('Supabase is not configured');
        }

        const { data, error } = await supabaseAdmin
            .from('order')
            .select('*')
            .eq('id', id)
            .single();

        if (error) {
            if (error.code === 'PGRST116') {
                return null; // Not found
            }
            throw new Error(`Failed to get order: ${error.message}`);
        }

        return data;
    },

    /**
     * Get order by order code (UUID)
     */
    async getByCode(code: string): Promise<Order | null> {
        if (!isSupabaseConfigured()) {
            throw new Error('Supabase is not configured');
        }

        const { data, error } = await supabaseAdmin
            .from('order')
            .select('*')
            .eq('code', code)
            .single();

        if (error) {
            if (error.code === 'PGRST116') {
                return null;
            }
            throw new Error(`Failed to get order: ${error.message}`);
        }

        return data;
    },

    /**
     * Get order by custom order code (DH...)
     * Searches in program_data or note field
     */
    async getByOrderCode(orderCode: string): Promise<Order | null> {
        if (!isSupabaseConfigured()) {
            throw new Error('Supabase is not configured');
        }

        // First try to find in program_data
        const { data, error } = await supabaseAdmin
            .from('order')
            .select('*')
            .contains('program_data', { orderCode })
            .single();

        if (!error && data) {
            return data;
        }

        // Fallback: search orders with matching note/content
        const { data: orders, error: searchError } = await supabaseAdmin
            .from('order')
            .select('*')
            .like('note', `%${orderCode}%`)
            .limit(1);

        if (searchError) {
            throw new Error(`Failed to search order: ${searchError.message}`);
        }

        return orders?.[0] || null;
    },

    /**
     * Get order with transaction details
     */
    async getWithTransaction(orderId: number): Promise<OrderWithTransaction | null> {
        if (!isSupabaseConfigured()) {
            throw new Error('Supabase is not configured');
        }

        const { data: order, error: orderError } = await supabaseAdmin
            .from('order')
            .select('*')
            .eq('id', orderId)
            .single();

        if (orderError || !order) {
            return null;
        }

        // Get associated transaction if exists
        if (order.transaction_id) {
            const { data: transaction } = await supabaseAdmin
                .from('transactions')
                .select('id, status, gateway_transaction_id, qr_code_url')
                .eq('id', order.transaction_id)
                .single();

            return { ...order, transaction };
        }

        return order;
    },

    /**
     * Update order status
     */
    async updateStatus(id: number, status: OrderStatus): Promise<Order> {
        if (!isSupabaseConfigured()) {
            throw new Error('Supabase is not configured');
        }

        const { data, error } = await supabaseAdmin
            .from('order')
            .update({ status, update_at: new Date().toISOString() })
            .eq('id', id)
            .select()
            .single();

        if (error) {
            throw new Error(`Failed to update order status: ${error.message}`);
        }

        return data;
    },

    /**
     * Update order with transaction ID
     */
    async setTransactionId(orderId: number, transactionId: number): Promise<void> {
        if (!isSupabaseConfigured()) {
            throw new Error('Supabase is not configured');
        }

        const { error } = await supabaseAdmin
            .from('order')
            .update({ transaction_id: transactionId, update_at: new Date().toISOString() })
            .eq('id', orderId);

        if (error) {
            throw new Error(`Failed to set transaction ID: ${error.message}`);
        }
    },

    /**
     * Update order with receipt ID
     */
    async setReceiptId(orderId: number, receiptId: number): Promise<void> {
        if (!isSupabaseConfigured()) {
            throw new Error('Supabase is not configured');
        }

        const { error } = await supabaseAdmin
            .from('order')
            .update({ receipt_id: receiptId, update_at: new Date().toISOString() })
            .eq('id', orderId);

        if (error) {
            throw new Error(`Failed to set receipt ID: ${error.message}`);
        }
    },

    /**
     * Update order data
     */
    async update(id: number, data: OrderUpdate): Promise<Order> {
        if (!isSupabaseConfigured()) {
            throw new Error('Supabase is not configured');
        }

        const { data: order, error } = await supabaseAdmin
            .from('order')
            .update({ ...data, update_at: new Date().toISOString() })
            .eq('id', id)
            .select()
            .single();

        if (error) {
            throw new Error(`Failed to update order: ${error.message}`);
        }

        return order;
    },

    /**
     * Get orders by email
     */
    async getByEmail(email: string): Promise<Order[]> {
        if (!isSupabaseConfigured()) {
            throw new Error('Supabase is not configured');
        }

        const { data, error } = await supabaseAdmin
            .from('order')
            .select('*')
            .eq('email', email)
            .order('created_at', { ascending: false });

        if (error) {
            throw new Error(`Failed to get orders: ${error.message}`);
        }

        return data || [];
    },

    /**
     * List orders with pagination
     */
    async list(options: {
        limit?: number;
        offset?: number;
        status?: OrderStatus;
    } = {}): Promise<{ orders: Order[]; count: number }> {
        if (!isSupabaseConfigured()) {
            throw new Error('Supabase is not configured');
        }

        const { limit = 50, offset = 0, status } = options;

        let query = supabaseAdmin
            .from('order')
            .select('*', { count: 'exact' })
            .order('created_at', { ascending: false })
            .range(offset, offset + limit - 1);

        if (status !== undefined) {
            query = query.eq('status', status);
        }

        const { data, error, count } = await query;

        if (error) {
            throw new Error(`Failed to list orders: ${error.message}`);
        }

        return { orders: data || [], count: count || 0 };
    },
};
